# tickers.py — NSE Nifty 500 symbols (plain, no .NS suffix)

NSE_TICKERS = [
    # NIFTY 50
    "RELIANCE","TCS","HDFCBANK","ICICIBANK","BHARTIARTL",
    "SBIN","INFY","HINDUNILVR","ITC","KOTAKBANK",
    "LT","HCLTECH","BAJFINANCE","MARUTI","SUNPHARMA",
    "NTPC","ONGC","TITAN","ULTRACEMCO","ADANIENT",
    "ADANIPORTS","ASIANPAINT","AXISBANK","BAJAJFINSV","BAJAJ-AUTO",
    "BPCL","BRITANNIA","CIPLA","COALINDIA","DIVISLAB",
    "DRREDDY","EICHERMOT","GRASIM","HDFCLIFE","HEROMOTOCO",
    "HINDALCO","INDUSINDBK","JSWSTEEL","M&M","NESTLEIND",
    "POWERGRID","SBILIFE","SHRIRAMFIN","TATACONSUM","TATAMOTORS",
    "TATASTEEL","TECHM","WIPRO","APOLLOHOSP","LTIM",

    # NIFTY NEXT 50
    "ABB","ADANIGREEN","AMBUJACEM","AUROPHARMA","BANKBARODA",
    "BERGEPAINT","BOSCHLTD","CANBK","CHOLAFIN","COLPAL",
    "DABUR","DLF","GAIL","GODREJCP","HAVELLS",
    "ICICIGI","ICICIPRULI","INDUSTOWER","INDIGO","IOC",
    "IRFC","JINDALSTEL","LUPIN","MARICO","MUTHOOTFIN",
    "NAUKRI","OFSS","PAGEIND","PIDILITIND","PNB",
    "RECLTD","SIEMENS","SRF","TATAPOWER","TORNTPHARM",
    "TRENT","VBL","VEDL","ZOMATO","DMART",

    # NIFTY MIDCAP
    "ABCAPITAL","ASHOKLEY","ASTRAL","AUBANK","BALKRISIND",
    "BANDHANBNK","BEL","BHEL","BIOCON","CAMS",
    "CANFINHOME","CONCOR","COROMANDEL","CROMPTON","CUMMINSIND",
    "DEEPAKNTR","ESCORTS","EXIDEIND","FEDERALBNK","GMRINFRA",
    "GODREJPROP","GUJGASLTD","HAL","HINDPETRO","IDFCFIRSTB",
    "IGL","INDHOTEL","INDIAMART","JUBLFOOD","KANSAINER",
    "LICHSGFIN","LTTS","MANAPPURAM","MAXHEALTH","MCX",
    "MFSL","MGL","MOTHERSON","MPHASIS","MRF",
    "NATIONALUM","NAVINFLUOR","NMDC","OBEROIRLTY","PERSISTENT",

    # SMALLCAP / OTHERS
    "AARTIIND","AJANTPHARM","ALKEM","ANGELONE","APOLLOTYRE",
    "BATAINDIA","BLUESTARCO","CARBORUNIV","CASTROLIND","CENTURYTEX",
    "CHAMBLFERT","CLEAN","CYIENT","DATAPATTNS","DELTACORP",
    "EIDPARRY","ELGIEQUIP","EMAMILTD","ENDURANCE","FINEORG",
    "GLENMARK","GNFC","GODFRYPHLP","GRINDWELL","GSFC",
    "HFCL","IPCALAB","IRCTC","ISEC","JBCHEPHARM",
    "KAJARIACER","KEI","METROPOLIS","NATCOPHARM","NUVOCO",
    "POLYMED","RAJESHEXPO","REDINGTON","ROSSARI","ROUTE",
    "SAFARI","SOLARINDS","STAR","TASTYBITE","TIINDIA",
    "TTKPRESTIG","VGUARD","VINATIORGA","WONDERLA","ZENSARTECH",
]
